services:
  databox:
    image: ghcr.io/knom/databox
    container_name: databox
    environment:
      - Logging:LogLevel:Databox=Information
      - App:BasePath=/databox
      - App:BaseUrl=http://localhost/databox/
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./docker/data:/app/data
      - ./docker/logs:/app/logs
      - ./uploads/:/app/uploads/
    restart: always
